#!/bin/bash

function af() {
    (
        source "${HOME}/iCloudDocs/Programming/Mailserver/Mailu/aws/admin-functions"
        "$@"
    )
}


#####
#
# FIXME -- list prerequisites and assumptions
#
# http://169.254.169.254/latest/meta-data/instance-id
# http://169.254.169.254/latest/meta-data/placement/availability-zone
# http://169.254.169.254/latest/meta-data/local-ipv4
# http://169.254.169.254/latest/meta-data/local-hostname
# http://169.254.169.254/latest/meta-data/public-hostname
# http://169.254.169.254/latest/meta-data/public-ipv4
#
# aws secretsmanager create-secret \
#       --name mailserver.admin-credentials \
#       --secret-string '{"username":"postmaster","password":"postmaster"}' \
#       --tags '[{"Key":"Name","Value":"mailserver:admin-credentials"},{"Key":"Role","Value":"mailserver"}]'
#       --description 'Mailserver administrator account name and password'
# aws secretsmanager get-secret-value --secret-id  mailserver.admin-credentials  | jq '.SecretString'  | sed -E 's/(^"|"$)//g' | sed 's/\\"/"/g' | jq -r '.password'
# aws secretsmanager list-secrets
#
#####

export MAILSERVER_HOME=${MAILSERVER_HOME:-/var/lib/mailu}
export MAILSERVER_CONFIGURATION_FILE=${MAILSERVER_CONFIGURATION_FILE:-${MAILSERVER_HOME}/mailu.env}
export MAILSERVER_KEY_PAIR=mailserver.hanlonsoftware.com
export MAILSERVER_INSTANCE_PROFILE=Mailserver@jim.hanlonsoftware.com
export MAILSERVER_INSTANCE_TYPE=t3.medium
export MAILSERVER_UBUNTU_RELEASE=focal

prg=${BASH_SOURCE[0]}
[[ ( -n "${prg}" ) && ( -f "${prg}" ) ]] || (echo "[FATAL] cannot locate: '$0'" 1>&2)
task=$(basename -- "${prg}")
prgdir=$(dirname -- "${prg}")
prgdir=$(cd "${prgdir}" > /dev/null && pwd)

source "${prgdir}/route-53-functions"


function instance:read-tag() {
    local instanceId=${1:?Need instance ID}
    local key=${2:?Need key}
    # local region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')
    aws ec2 describe-tags --filters Name=resource-id,Values=${instanceId} Name=key,Values=$key | jq -r '.Tags[].Value'
}


function instance:set-a-records() {
    route-53:set-ipv4-a-record 300 "${@}"
}


function instance:set-cname-records() {
    route-53:set-cname-record 300 "${@}"
}


function mailserver:authorize-my-ip-for-ssh-ingress() {
    local myIp=$(dig +short myip.opendns.com @resolver1.opendns.com)
    local securityGroup=$(mailserver:get-security-group)
    aws ec2 authorize-security-group-ingress \
        --group-id "${securityGroup}" \
        --protocol tcp \
        --port 22 \
        --cidr "${myIp}/32" \
        --output text
}


mailserver:create-instance() {
    # local postmasterPassword=${1:?Need postmaster password)
    echo "[INFO] looking for latest Ubuntu AMI" >/dev/stderr
    local ami=$(ubuntu:find-latest-ami)
    echo "[INFO] using AMI ${ami}" >/dev/stderr
    local sg=$(mailserver:get-security-group)
    echo "[INFO] using security group ${sg}" >/dev/stderr
    local subnet=$(util:find-random-subnet)
    echo "[INFO] using subnet ${subnet}" >/dev/stderr
    local response=$(aws ec2 run-instances \
        --image-id "${ami}" \
        --count 1 \
        --instance-type "${MAILSERVER_INSTANCE_TYPE}" \
        --key-name "${MAILSERVER_KEY_PAIR}" \
        --security-group-ids "${sg}" \
        --subnet-id "${subnet}" \
        --instance-initiated-shutdown-behavior terminate \
        --user-data file:///dev/stdin <<EOF
#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export MAILSERVER_HOME=/var/lib/mailu

function create-aws-instance-tag() {
    local key=\${1:?Need key}
    local value=\${2?Need value}
    local instanceId=\$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
    local region=\$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | cut -d\" -f4)
    aws ec2 create-tags --region "\${region}" --resources "\${instanceId}" --tags Key="\${key}",Value="\${value}"
}

create-aws-instance-tag BootstrapStatus 'installing required packages'
apt-get update
apt-get upgrade -y
apt-get install -y \
    apt-transport-https \
    apt-utils
apt-get install -y \
    awscli \
    binutils \
    ca-certificates \
    cron \
    curl \
    git \
    gnupg-agent \
    jq \
    net-tools \
    nfs-common \
    python3 \
    python3-pip \
    software-properties-common \
    sqlite3 \
    vim
(
    git clone https://github.com/aws/efs-utils
    (
        cd efs-utils;
        ./build-deb.sh
        apt-get -y install ./build/amazon-efs-utils*deb
    )
    rm -rf efs-utils
)
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn apt-key add -
(echo -n "deb [arch=amd64] https://download.docker.com/linux/ubuntu "; lsb_release -cs | tr -c -d '[:alpha:]'; echo ' stable') > /etc/apt/sources.list.d/docker.sources.list
apt-get update
apt-get install -y \
    docker-ce \
    docker-ce-cli \
    containerd.io
groupadd docker
usermod -aG docker ubuntu
pip3 install docker-compose
mkdir -p \${MAILSERVER_HOME}
git clone https://github.com/jim-hanlon/m-s \${MAILSERVER_HOME}

(echo &&
 echo 'export MAILSERVER_HOME="\${MAILSERVER_HOME}" && '
 echo 'cd "\${MAILSERVER_HOME}"'
) >> /home/ubuntu/.bashrc

source  \${MAILSERVER_HOME}/server-functions
mailserver:install
EOF
)
    local instance=$(echo "$response" | jq '.Instances[0].InstanceId' | sed -E 's/(^"|"$)//g')
    if [[ -n "${instance}" ]]; then
        echo "[INFO] created instance ${instance} ... waiting for it to start" >/dev/stderr
        while [[ $(util:instance-state "${instance}") != 'running' ]]; do sleep 5; done
        echo "[INFO] instance ${instance} is running" >/dev/stderr
        local hostname=$(util:instance-public-hostname "${instance}")
        echo "[INFO] setting ${instance} security profile" >/dev/stderr
        aws ec2 associate-iam-instance-profile \
            --instance-id ${instance} \
            --iam-instance-profile Name=${MAILSERVER_INSTANCE_PROFILE}
        echo "[INFO] created instance ${instance} @ ${hostname}" >/dev/stderr
        echo -n "[INFO] waiting for instance bootstrap to complete " >/dev/stderr
        local lastBootstrapStatus=$(instance:read-tag ${instance} BootstrapStatus)
        while [[ "${lastBootstrapStatus}" != 'complete' ]]; do
            local s=$(instance:read-tag ${instance} BootstrapStatus)
            if [[ "${s}" != "${lastBootstrapStatus}" ]]; then
                echo
                echo -n "[INFO] instance ${instance} is ${s}" >/dev/stderr
            fi
            lastBootstrapStatus="${s}"
            if [[ "${lastBootstrapStatus}" != 'complete' ]]; then
                sleep 5
                echo -n '.'
            fi
        done
        echo >/dev/stderr
        echo "[INFO] instance bootstrap is complete" >/dev/stderr
        echo "[INFO] remember to change the password for user 'postmaster'" >/dev/stderr
    else
        echo "[ERROR] failed to create instance" >/dev/stderr
        echo "[ERROR] ${response}" >/dev/stderr
        return 1
    fi
}


function mailserver:get-security-group() {
    aws ec2 describe-security-groups \
        --query 'SecurityGroups[*][Tags[?Key==`Name` && Value==`mailserver`].Value|[0], GroupId]' \
        --output text | \
    grep -E '^mailserver\s' | \
    awk '{ print $2 }'
}


function ubuntu:find-latest-ami() {
    local ubuntuOwnerId=099720109477
    local ubuntuRelease=${1:-${MAILSERVER_UBUNTU_RELEASE}}
    local ubuntuImagePrefix=${2:-ubuntu-minimal/images/hvm-ssd/}
    aws ec2 describe-images \
        --owners "${ubuntuOwnerId}" \
        --query 'Images[*].[CreationDate,Name,ImageId]' \
        --filters Name=root-device-type,Values=ebs \
                  Name=image-type,Values=machine \
                  Name=is-public,Values=true \
                  Name=hypervisor,Values=xen \
                  Name=architecture,Values=x86_64 \
                  Name=virtualization-type,Values=hvm \
        --output text | \
    grep "${ubuntuImagePrefix}"'.*'"${ubuntuRelease}"'.*' | \
    sort -r | \
    head -1 |
    awk '{ print $3 }'
}

function util:find-availability-zones() {
    aws ec2 describe-instance-type-offerings \
        --filters Name=instance-type,Values=${MAILSERVER_INSTANCE_TYPE} \
        --location-type availability-zone | \
    jq '.InstanceTypeOfferings[].Location' | \
    sed -E 's/(^"|"$)//g'
}

function util:find-random-subnet() {
    local az=$(util:find-availability-zones | \
               shuf --random-source /dev/random -n 1)
    aws ec2 describe-subnets \
        --filters "Name=availability-zone,Values=${az}" | \
    jq '.Subnets[].SubnetId' | \
    sed -E 's/(^"|"$)//g' | \
    shuf --random-source /dev/random -n 1
}

function util:instance-by-name() {
    local name=${1:?Need CNAME}
    aws ec2 describe-instances \
        --query 'Reservations[*].Instances[*][].[InstanceId, Tags[?starts_with(Key, `Name`)].Value|join(`:`,@)]' --output text |
    grep "${name}" | awk '{print $1}'
}


function util:instance-name() {
    local instanceId=${1:?Need Instance ID}
    util:instance-data "${instanceId}" | awk '{$1="";$2="";$3="";$4="";print $0}' | sed -E 's/(^[ ]+|[ ]+$)//g' | tr '[:space:]' '\n'
}


function util:instance-data() {
    local instanceId=${1:-""}
    local filters=$([[ -n "${instanceId}" ]] && echo "--filters Name=instance-id,Values=${instanceId}")
    aws ec2 describe-instances \
        ${filters} \
        --query 'Reservations[*].Instances[*].[InstanceId, State.Name, PublicDnsName, PublicIpAddress, Tags[?Key==`Name`].Value|[0]][]' --output text
}


function util:instance-data-by-name() {
    local name=${1:?Need NAME}
    util:instance-data | grep "${name}"
}


function util:instance-data-by-state() {
    local state=${1:?Need state}
    util:instance-data | awk '$2 == "'${state}'" { print $0 }'
}


function util:instance-ids() {
    util:instance-data | awk '{ printf("%s\n", $1) }'
}


function util:instance-public-hostname() {
    local instanceId=${1:?Need instance-id}
    util:instance-data "${instanceId}" | awk '{ print ($3 == "None" ? "" : $3); }'
}


function util:instance-public-hostnames() {
    util:instance-data | awk '{ print $1, ($3 == "None" ? "" : $3) }'
}


function util:instance-start() {
    util:start-instance "${@}"
}


function util:instance-states() {
    util:instance-data | awk '{ print $1, $2; }'
}


function util:instance-state() {
    local instanceId=${1:?Need instance ID}
    local filters="--filters Name=instance-id,Values=${instanceId}"
    aws ec2 describe-instances  --query 'Reservations[].Instances[].State.Name' ${filters} --output text
}


function util:instance-state-by-name() {
    local name=${1:?Need NAME}
    util:instance-data-by-name "${name}" | awk '{ printf("%s\n", $2) }'
}


function util:instance-tags() {
    local instanceId=${1:?Need Instance ID}
    aws ec2 describe-instances  --query 'Reservations[].Instances[?InstanceId==`'"${instanceId}"'`][].Tags[]' --output text
}


function util:start-instance() {
    local instanceId=${1:?Need Instance ID}
    local response=$(aws ec2 start-instances --instance-ids "${instanceId}")
    if [[ ${?} -ne 0 ]]; then
        echo "[ERROR] Unable to restart instance ${instanceId}\n${response}" > /dev/stderr && exit 1
    fi
    response=$(aws ec2 wait instance-running --instance-ids "${instanceId}" )
    if [[ ${?} -ne 0 ]]; then
        echo "[ERROR] Failure waiting for instance ${instanceId} to start\n${response}" > /dev/stderr && exit 1
    fi
}


function util:start-instance-by-name() {
    local name=${1:?Need NAME}
    util:start-instance $(util:instance-by-name "${name}")
}


function util:stop-instance() {
    local instanceId=${1:?Need Instance ID}
    
    local response=$(aws ec2 stop-instances --instance-ids "${instanceId}")
    if [[ ${?} -ne 0 ]]; then
        echo "[ERROR] Unable to stop instance ${instanceId}\n${response}" > /dev/stderr && exit 1
    fi
    response=$(aws ec2 wait instance-stopped --instance-ids "${instanceId}" )
    if [[ ${?} -ne 0 ]]; then
        echo "[ERROR] Failure waiting for instance ${instanceId} to stop\n${response}" > /dev/stderr && exit 1
    fi
}


function util:stop-instance-by-name() {
    local name=${1:?Need NAME}
    util:stop-instance $(util:instance-by-name "${name}")
}


function util:terminate-instances() {
    local instanceId=${1:?Need Instance ID}
    aws ec2 terminate-instances --instance-ids "${@}" --output text
}

function util:terminate-running-instances() {
    util:terminate-instance  $(util:instance-data | grep running | awk '{print $1}')
}

