#!/bin/bash

function route-53:delete-record {
    for name in "${@}"; do
        local domainName=$(echo "${name}" | sed -E 's/^[^\.]*\.//')
        local hostedZoneId=$(aws route53 list-hosted-zones --output text | grep "${domainName}" | awk '{print $3}' | cut -d/ -f3)
        local type=$(route-53:get-record-type "${name}")
        if [[ -n "${type}" ]]; then
            local ttl=$(route-53:get-record-ttl "${name}")
            local value=$(route-53:get-record-value "${name}")
            local result=$(aws route53 change-resource-record-sets --hosted-zone-id "${hostedZoneId}" --change-batch file:///dev/stdin <<END_OF_JSON
{
    "Changes": [
        {
            "Action": "DELETE",
            "ResourceRecordSet": {
                "Name": "${name}.",
                "Type": "${type}",
                "TTL": ${ttl},
                "ResourceRecords": [
                    {
                        "Value": "${value}"
                    }
                ]                
            }
        }
    ]
}
END_OF_JSON
            )
        fi
    done
}


function route-53:get-record-info() {
    local name=
    for name in "${@}"; do
        local domain="${name}"
        if (( $(echo "${name}" | tr '.' ' ' | wc -w) > 2 )); then
            domain=$(echo "${name}" | sed -E 's/^[^\.]*\.//')
        fi
        local id=$(route-53:get-zone-id "${domain}")
        local result=$(aws route53 list-resource-record-sets --hosted-zone-id "${id}" --query "ResourceRecordSets[?Name == '${name#.}.']")
        if [[ $(echo "${result}" | jq length) != '0' ]]; then
            local type=$(echo "${result}" | jq -r .[0].Type)
            local ttl=$(echo "${result}" | jq -r .[0].TTL)
            local value=$(echo "${result}" | jq -r .[0].ResourceRecords[0].Value)
            echo ${id} ${domain} ${name} ${type} ${ttl} ${value}
        else
            echo ${id} ${domain} ${name} - - -
        fi
    done
}


function route-53:get-record-ttl() {
    local name=${1:?Need Record Name}
    local domainName=$(echo "${name}" | sed -E 's/^[^\.]*\.//')
    local id=$(route-53:get-zone-id "${domainName}")
    aws route53 list-resource-record-sets --hosted-zone-id "${id}" --query "ResourceRecordSets[?Name == '${name#.}.']" | \
    jq -r .[0].TTL
}


function route-53:get-record-type() {
    local name=${1:?Need Record Name}
    local domainName=$(echo "${name}" | sed -E 's/^[^\.]*\.//')
    local id=$(route-53:get-zone-id "${domainName}")
    aws route53 list-resource-record-sets --hosted-zone-id "${id}" --query "ResourceRecordSets[?Name == '${name#.}.']" | \
    jq -r .[0].Type
}


function route-53:get-record-value() {
    local name=${1:?Need Record Name}
    local domainName=$(echo "${name}" | sed -E 's/^[^\.]*\.//')
    local id=$(route-53:get-zone-id "${domainName}")
    aws route53 list-resource-record-sets --hosted-zone-id "${id}" --query "ResourceRecordSets[?Name == '${name#.}.']" | \
    jq -r .[0].ResourceRecords[0].Value
}


function route-53:get-zone-id() {
    local name=${1:?Need Zone Name}
    aws route53 list-hosted-zones --query "HostedZones[?Name == '${name#.}.']" | \
    jq -r .[0].Id | \
    cut -d/ -f3
}

function route-53:get-zone-name() {
    local id=${1:?Need Zone ID}
    aws route53 get-hosted-zone --id "${id}" | \
    jq -r '.HostedZone.Name' | \
    sed 's/\.$//'
}


function route-53:list-zones() {
    aws route53 list-hosted-zones --output text | \
    grep HOSTEDZONES | \
    awk '{ print $4, $3 }' | \
    sed 's|. /hostedzone/| |' | \
    awk '{ print $2, $1 }'
}


function route-53:set-cname-record() {
    # args: cname TTL [recordname ...]
    route-53:set-ipv4-a-or-cname-record 'CNAME' "${@}"
}


function route-53:set-ipv4-a-record() {
    # args: ipv4 TTL [recordname ...]
    route-53:set-ipv4-a-or-cname-record 'A' "${@}"
}


function route-53:set-ipv4-a-or-cname-record() {
    local type=${1:?Need record type}
    shift
    local address=${1:?Need  address}
    shift
    local ttl=${1:-300}
    shift
    for name in "${@}"; do
        local domainName=$(echo "${name}" | sed -E 's/^[^\.]*\.//')
        local hostedZoneId=$(aws route53 list-hosted-zones --output text | grep  "\s${domainName}\.\s" | awk '{print $3}' | cut -d/ -f3)
        local t=$(route-53:get-record-type "${name}")
        [[ -n "${t}" && "${t}" != "${type}" ]] && route-53:delete-record "${name}"
        local result=$(aws route53 change-resource-record-sets --hosted-zone-id "${hostedZoneId}" --change-batch file:///dev/stdin <<END_OF_JSON
{
  "Changes": [
    {
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "${name}.",
        "Type": "${type}",
        "TTL": ${ttl},
        "ResourceRecords": [
          {
            "Value": "${address}"
          }
        ]
      }
    }
  ]
}
END_OF_JSON
        )
    done
}


function route-53:create-resource-record-changes-subset() {
    [[ -z "${1:-}" ]] && echo "${FUNCNAME[0]} domain type value ttl [name ...]" >/dev/stderr && return
    local domain=${1:?Need domain}
    local type=${2:?Need record type}
    local value=${3:?Need value}
    local ttl=${4:-300}
    shift 4
    for name in "${@}"; do
        echo "${name}"
    done | sort -u | while read name; do
        local target=${domain}
        [[ -n "${name}" ]] && target="${name}.${domain}"
        route-53:get-record-info "${target}"
    done | while read id _ name curtype curttl curvalue; do
        if [[ "${type}" != "${curtype}" ]] || [[ "${ttl}" != "${curttl}" ]] || [[ "${value}" != "${curvalue}" ]]; then
            if [[ "${type}" != "${curtype}" ]] && [[ "${curtype}" != "-" ]]; then
                echo "{\"Action\":\"DELETE\",\"ResourceRecordSet\":{\"Name\":\"${name}.\",\"Type\":\"${curtype}\",\"TTL\":${curttl},\"ResourceRecords\":[{\"Value\":\"${curvalue}\"}]}},"
            fi
            echo "{\"Action\":\"UPSERT\",\"ResourceRecordSet\":{\"Name\":\"${name}.\",\"Type\":\"${type}\",\"TTL\":${ttl},\"ResourceRecords\":[{\"Value\":\"${value}\"}]}},"
        fi
    done
}
